apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: java-quarkus-170258267
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/user1-tenant/test-app-170258267/java-quarkus-170258267@sha256:6767c2dd768bf62c27da23f1dd084c849e375f489e4a4b8ec5409be61b688a30
        name: my-java-quarkus
        resources: {}
status: {}
